dbt_airflow_patrick:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: airflow
      password: airflow
      port: 5432
      database: airflow
      schema: "public"
      # threads: 2
      # keepalives_idle: 0 # default 0, indicating the system default. See below
      # connect_timeout: 30 # default 10 seconds
      # search_path: [optional, override the default postgres search_path]
      # role: [optional, set the role dbt assumes when executing queries]
      # sslmode: [optional, set the sslmode used to connect to the database]
