
version: 2

models:
  - name: d_gender_count
    description: "A starter dbt model"
    columns:
      - name: Gender_Type
        description: "The primary key for this table"
      - name: Gender_Count
        description: "Count of gender"